spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 9300
      discovery:
        instanceId: ${spring.application.name}
        hostname: localhost
---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   show-sql: true
   hibernate.ddl-auto: update
# ---
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/microservice
#     username: admin
#     password: admin
#   jpa:
#    show-sql: true
#    hibernate.ddl-auto: update


                


