spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 9300
      discovery:
        instanceId: ${spring.application.name}
        hostname: localhost



---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
   show-sql: true
   hibernate.ddl-auto: update
